name: testado
on:
  push:
    branches: [main]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v4.1.8
        with:
          SSH_PRIVATE_KEY: ${{secrets.SSH_KEY}}
          REMOTE_HOST: ${{secrets.SSH_HOST}}
          REMOTE_USER: ${{secrets.SSH_USERNAME}}
          TARGET: /home/axondev/
          SCRIPT_BEFORE: touch text.txt
          SCRIPT_AFTER: touch text_1.txt 
